# Generated by Django 5.2.3 on 2025-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='New', help_text='The current status of the applicant in the hiring pipeline.', max_length=50),
        ),
    ]
