# Generated by Django 5.2.3 on 2025-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='original_cv',
            field=models.FileField(blank=True, help_text='Upload the original CV file', null=True, upload_to='resumes/'),
        ),
    ]
