# Generated by Django 5.2.3 on 2025-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resume_original_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
