# Generated by Django 5.2.3 on 2025-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resume_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.CharField(blank=True, help_text='AI-suggested job category', max_length=100, null=True),
        ),
    ]
