# Generated by Django 5.2.3 on 2025-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resume_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='api.category'),
        ),
    ]
