# Generated by Django 5.2.3 on 2025-06-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_remove_resume_category_resume_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='rating',
            field=models.IntegerField(blank=True, help_text='AI-generated rating from 1 to 10', null=True),
        ),
    ]
